Minor corrections (non-content related)
tgdwyer/tgdwyer.github.io pull request #21
Opened 2020-08-19 08:31 UTC by NitinMa2

Hey Tim,

Just correct some grammar mistakes!

Cheers,
Nitin

2020-08-19 10:51 UTC, tgdwyer requested changes
Thanks for this, but not quite right, the first should be:
difficult-to-diagnose bugs

The second is good though.

2020-08-19 10:59 UTC, NitinMa2 commented
Awesome! Thanks for clarifying.

2020-08-19 15:04 UTC, NitinMa2 commented
I just noticed that you had "requested" a change! I have already attended to it.

2020-08-20 02:21 UTC, tgdwyer approved these changes

2020-08-20 02:21 UTC, merged